## Application related configuration
spring:
  application:
    name: springbootmicrodatabase


## Server related configuration
server:
  port: 2222
  servlet:
    context-path: /springbootmicrodatabase


eureka:
  instance:
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
